    export const loginPage = 'https://deathstar-qa-candidate-test.herokuapp.com/'
    export const selectAllButton = 'div.src-views-styles__outerContainer__t63xn div:nth-child(2) div.styles_modal__1d9g1.styles_mobile-style__1d9g1 div.styles_main-content__1d9g1 div.styles_bottomContainer__1d9g1 > button.styles_linkContainer__eg3bl'
    export const headerItemPeople = '.src-components-core-Header-styles__tabRow__h63F6 > [data-automation="header-item-people"] > .src-components-core-Header-HeaderLink-styles__tabName__ywbSr > .styles_heading__1om0g'
    export const userEmail = '.styles_input__xphjl'
    export const userPassword = '.styles_input__xphjl'
    export const continueButton = '.styles_primary__hk7t8'
    export const clickOnPeople = '.styles_primary__hk7t8 > .styles_contentWithIconContainer__hk7t8 > :nth-child(2) > .styles_heading__1om0g'
    export const addSingleUser = '.styles_scrollContainer__1nh44 > :nth-child(1) > .styles_linkContainer__eg3bl > .styles_primary__eg3bl'
    export  const firstName = '.src-components-peopleAndTeams-EditMember-styles__userDetailsHeader__bS2NY > :nth-child(1) > .styles_inputContainer__xphjl > .styles_input__xphjl'
    export const lastName = ':nth-child(2) > .styles_inputContainer__xphjl > .styles_input__xphjl'
    export const otherInfoTYpeIn = '.src-components-peopleAndTeams-EditMember-styles__otherInfoWrapper__ghFVw > :nth-child(2) > .styles_container__xphjl > .styles_inputContainer__xphjl > .styles_input__xphjl'
    export const clickOnSelectTeams = '.src-components-peopleAndTeams-EditMember-styles__otherButtonWrapper__MzW6q > :nth-child(1) > .styles_primary__hk7t8'
    export const selectButton = '#react-aria-modal-dialog > div > div > div.styles_bottomContainer__1d9g1 > span > button'
    export const addUser = '#appContent > div > div > div:nth-child(3) > form > div > div.src-components-core-FocusElement-styles__outer-container__OuL6j > div > div > div.src-components-peopleAndTeams-EditMember-styles__buttonWrapper__Ro6QI > span.src-components-peopleAndTeams-EditMember-styles__otherButtonWrapper__MzW6q > div:nth-child(1) > button.styles_primary__hk7t8.styles_button__hk7t8.styles_noMarginTop__hk7t8'
    export const clickOnEmailButton = ':nth-child(1) > .styles_circle__1emt1 > .styles_innerCircle__1emt1'
    export const enterValidEmail = '.src-components-peopleAndTeams-EditMember-styles__editForm__lwsAU > .styles_container__xphjl > .styles_inputContainer__xphjl > .styles_input__xphjl'
    export const phoneNumberButton = ':nth-child(3) > .styles_circle__1emt1'
    export const validPhoneNumber = '.styles_phoneInput__19n3c > .styles_container__xphjl > .styles_inputContainer__xphjl > .styles_input__xphjl'